// @flow
// i18n
export const SET_I18N = 'SET_I18N';

// snack
export const SET_AND_SHOW_ERROR = 'SET_AND_SHOW_ERROR';
export const SET_AND_SHOW_WARNING = 'SET_AND_SHOW_WARNING';
export const SET_AND_SHOW_INFO = 'SET_AND_SHOW_INFO';
export const SET_AND_SHOW_SERVER_ERROR = 'SET_AND_SHOW_SERVER_ERROR';
export const CLEAR_SNACK = 'CLEAR_SNACK';

// globalUi
export const SET_LOADING = 'SET_LOADING';
export const UNSET_LOADING = 'UNSET_LOADING';
export const SET_LOGIN_OR_REGISTER = 'SET_LOGIN_OR_REGISTER';
export const UNSET_LOGIN_OR_REGISTER = 'UNSET_LOGIN_OR_REGISTER';
export const SET_PASSWORD_FORGOTTEN_TYPE = 'SET_PASSWORD_FORGOTTEN_TYPE';
export const SET_EDIT_PROFILE = 'SET_EDIT_PROFILE';
export const UNSET_EDIT_PROFILE = 'UNSET_EDIT_PROFILE';

// login
export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_PASSWORD = 'SET_PASSWORD';

// registration
export const SET_TITLE = 'SET_TITLE';
export const SET_GENDER = 'SET_GENDER';
export const SET_FIRST_NAME = 'SET_FIRST_NAME';
export const SET_LAST_NAME = 'SET_LAST_NAME';
export const SET_EMAIL = 'SET_EMAIL';
export const SET_ORGANISATION = 'SET_ORGANISATION';
export const SET_ADDRESS = 'SET_ADDRESS';
export const SET_CITY = 'SET_CITY';
export const SET_COUNTY = 'SET_COUNTRY';
export const SET_ZIP_CODE = 'SET_ZIP_CODE';
export const SET_FIELD_OF_ACTIVITY = 'SET_FIELD_OF_ACTIVITY';
export const SET_RESEARCH_INTERESTS = 'SET_RESEARCH_INTERESTS';
export const SET_SECURITY_QUESTION = 'SET_SECURITY_QUESTION';
export const SET_SECURITY_ANSWER = 'SET_SECURITY_ANSWER';

// collections
export const SET_COLLECTION_SECURITY_QUESTION = 'SET_COLLECTION_SECURITY_QUESTION';
export const SET_COLLECTION_RESEARCH_INTERESTS = 'SET_COLLECTION_RESEARCH_INTERESTS';

// user
export const SET_ACTIVE_USER = 'SET_ACTIVE_USER';

// password reset
export const SET_RESET_EMAIL = 'SET_RESET_EMAIL';
export const SET_PASSWORD_RESET_OBJECT = 'SET_PASSWORD_RESET_OBJECT';
export const SET_SECURITY_QUESTION_ANSWER = 'SET_SECURITY_QUESTION_ANSWER';
export const SET_NEW_PASSWORD = 'SET_NEW_PASSWORD';
export const SET_CHECK_PASSWORD = 'SET_CHECK_PASSWORD';

// profileview
export const SET_USER_PROFILE = 'SET_USER_PROFILE';
export const SET_ID = 'SET_ID';
